services:
  - type: web
    name: eduflow-owner-backend
    runtime: docker
    repo: https://github.com/Fhermei/eduflow-owner-panel
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health/
    
    envVars:
      - key: SECRET_KEY
        value: UffbAWaa_TYL8T1tTt5v0L_kr7FxAnlaXc8WwfjGny8
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com,eduflow-owner-backend.onrender.com
      - key: DATABASE_URL
        value: postgresql://postgres.weylcudtgzhshrgneshx:EduFlowBackend12@aws-0-eu-west-1.pooler.supabase.com:5432/postgres
      - key: DB_SSL_REQUIRE
        value: "true"
      - key: DJANGO_SUPERUSER_USERNAME
        value: owner_admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: owner@eduflow.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: SuperSecurePassword123!
      - key: CORS_ALLOWED_ORIGINS
        value: https://edu-flow-owner-frontend.vercel.app
      - key: CSRF_TRUSTED_ORIGINS
        value: https://edu-flow-owner-frontend.vercel.app
      - key: FRONTEND_URL
        value: https://edu-flow-owner-frontend.vercel.app