# Generated by Django 4.2.16 on 2026-07-02 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalFeeOwnerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_fee_amount', models.DecimalField(decimal_places=2, default=1000, help_text='Default portal fee amount for new schools', max_digits=10)),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portal Fee Owner Setting',
                'verbose_name_plural': 'Portal Fee Owner Settings',
            },
        ),
        migrations.CreateModel(
            name='PortalFeeSchoolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=1000, help_text='Portal fee amount for this school', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('custom_message', models.TextField(blank=True, help_text='Custom message for students/parents')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_fee_config', to='schools.school')),
            ],
            options={
                'verbose_name': 'Portal Fee School Config',
                'verbose_name_plural': 'Portal Fee School Configs',
            },
        ),
    ]
