# Generated by Django 4.2.16 on 2026-05-28 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_schools", models.IntegerField(default=0)),
                ("total_users", models.IntegerField(default=0)),
                ("total_students", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "portal_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("total_logins", models.IntegerField(default=0)),
                ("active_schools", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("db_name", models.CharField(max_length=100)),
                (
                    "api_url",
                    models.CharField(default="http://localhost:8001", max_length=200),
                ),
                (
                    "registration_prefix",
                    models.CharField(
                        default="EDU",
                        help_text="Prefix for registration numbers (e.g., EDU, PRIME, GF). Min 2 characters, max 10.",
                        max_length=10,
                    ),
                ),
                ("paystack_public_key", models.CharField(blank=True, max_length=200)),
                ("paystack_secret_key", models.CharField(blank=True, max_length=200)),
                ("portal_fee_public_key", models.CharField(blank=True, max_length=200)),
                ("portal_fee_secret_key", models.CharField(blank=True, max_length=200)),
                (
                    "portal_fee_amount",
                    models.DecimalField(decimal_places=2, default=1000, max_digits=10),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("archived_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SchoolMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_users", models.IntegerField(default=0)),
                ("active_users", models.IntegerField(default=0)),
                ("total_students", models.IntegerField(default=0)),
                ("active_students", models.IntegerField(default=0)),
                ("total_staff", models.IntegerField(default=0)),
                ("active_staff", models.IntegerField(default=0)),
                ("total_parents", models.IntegerField(default=0)),
                ("total_admins", models.IntegerField(default=0)),
                ("role_breakdown", models.JSONField(blank=True, default=dict)),
                ("school_fee_success", models.IntegerField(default=0)),
                ("school_fee_pending", models.IntegerField(default=0)),
                ("school_fee_failed", models.IntegerField(default=0)),
                (
                    "school_fee_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("portal_success", models.IntegerField(default=0)),
                ("portal_pending", models.IntegerField(default=0)),
                ("portal_failed", models.IntegerField(default=0)),
                (
                    "portal_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("portal_paid_count", models.IntegerField(default=0)),
                ("portal_pending_count", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("last_health_check", models.DateTimeField(blank=True, null=True)),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("unhealthy", "Unhealthy"),
                            ("down", "Down"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("response_time_ms", models.FloatField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("db_size_mb", models.FloatField(default=0)),
                ("media_size_mb", models.FloatField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("archive", "Archive"),
                            ("restore", "Restore"),
                            ("sync", "Sync"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("user", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
