# Generated by Django 4.2.16 on 2026-06-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
