# Generated by Django 4.2.16 on 2026-06-12 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_alter_activitylog_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(default="activity", max_length=100),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to="schools.school",
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="user",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["school", "-created_at"], name="schools_act_school__103c44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(fields=["action"], name="schools_act_action_8cc632_idx"),
        ),
    ]
