# Generated by Django 4.2.16 on 2026-06-12 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0003_alter_activitylog_action_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_number", models.CharField(db_index=True, max_length=50)),
                ("user_name", models.CharField(blank=True, max_length=200)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("was_successful", models.BooleanField(default=False)),
                ("failure_reason", models.CharField(blank=True, max_length=200)),
                (
                    "attempted_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
            ],
            options={
                "ordering": ["-attempted_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("registration_number", models.CharField(db_index=True, max_length=50)),
                ("user_name", models.CharField(blank=True, max_length=200)),
                ("user_role", models.CharField(blank=True, max_length=50)),
                (
                    "session_key",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("login_time", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True, db_index=True)),
                ("logout_time", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "ordering": ["-last_activity"],
            },
        ),
        migrations.RemoveIndex(
            model_name="activitylog",
            name="schools_act_action_8cc632_idx",
        ),
        migrations.AddField(
            model_name="activitylog",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="user_registration_number",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="user_role",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="user",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["action", "-created_at"], name="schools_act_action_aae3ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["user_registration_number", "-created_at"],
                name="schools_act_user_re_9bfb94_idx",
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_attempts",
                to="schools.school",
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["registration_number", "is_active"],
                name="schools_use_registr_09ff1b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["last_activity"], name="schools_use_last_ac_e9b512_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginattempt",
            index=models.Index(
                fields=["registration_number", "-attempted_at"],
                name="schools_log_registr_f20fdc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loginattempt",
            index=models.Index(
                fields=["ip_address", "-attempted_at"],
                name="schools_log_ip_addr_35304a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loginattempt",
            index=models.Index(
                fields=["attempted_at"], name="schools_log_attempt_249d2b_idx"
            ),
        ),
    ]
