# Generated by Django 4.2.16 on 2026-05-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backup", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backupschedule",
            name="day_of_month",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Day of month to run (1-28)"
            ),
        ),
    ]
