# Generated by Django 4.2.16 on 2026-05-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backup", "0002_alter_backupschedule_day_of_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backupschedule",
            name="day_of_month",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
